services:
  quantumqueue:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    environment:
      RABBITMQ_DEFAULT_USER:        scout
      RABBITMQ_DEFAULT_PASS:        passw0rd

  influxdb:
    image: influxdb:2.1
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: SuperSecretPa55
      DOCKER_INFLUXDB_INIT_ORG: XenoTelemetry
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
      DOCKER_INFLUXDB_INIT_RETENTION: 7d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: sk_xeno_admin_token
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.30
    depends_on:
      - quantumqueue
      - influxdb
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    ports:
      - "8125:8125/udp"  
volumes:
  influxdb_data: